version: "2.1"
services:
  web:
    build: .
    command: bash -c "npm install && NODE_ENV=${NODE_ENV:-production} npm run start"
    env_file:
      - .env
    volumes:
      - ./:/app/
      - ./node_modules/:/app/node_modules/
    ports:
      - 8080:3001
    links:
      - mongo
      
  mongo:
    image: mongo:4.2.1-bionic
    volumes:
      - ./mongo-data/:/data/db/
      - ./mongo-backup/:/mongo-backup/
    ports:
      - "27017:27017"
